### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by adammallo** [saidsef/k8s-nifi-cluster#21]
Not sure if this is an issue or just a problem with my deployment. When I run a "kubectl logs" on my nifi pods I keep seeing the following Exception. However, it is a little hard to complain because besides that things seem to be working. Wondering if you have seen (or are seeing) something similar, or if you might know how to resolve it? For what it is worth I really appreciate the effort you have put into this thus far.

2023-03-22 23:31:19,382 WARN [Process Cluster Protocol Request-2] o.a.n.c.p.impl.SocketProtocolListener Failed processing protocol message from **XXX.XX.XX.X** due to java.io.EOFException
java.io.EOFException: null
        at org.apache.nifi.cluster.protocol.jaxb.JaxbProtocolContext$2.unmarshal(JaxbProtocolContext.java:115)
        at org.apache.nifi.cluster.protocol.impl.SocketProtocolListener.dispatchRequest(SocketProtocolListener.java:150)
        at org.apache.nifi.io.socket.SocketListener$2$1.run(SocketListener.java:131)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by saidsef** [comment]
@adammallo I had a chance to look into this today, and it appears to be a NiFi issue when running in clustered mode.  Will need to do a further investigation - if I have time - and maybe created an issue in their project.

I can see there a new version out, perhaps upgrading might make fix it 🤔   #22

**Comment by adammallo** [comment]
@saidsef thanks for looking into it. I tried 1.20.0 as well and I still continually see that error. When you say it is NiFi running in clustered mode do you mean that pretty much anyone running NiFi clustered could expect to see this error? Are you also seeing it in your deployment?
If that is the case I am slightly surprised that no one also is complaining about it. I have not found very about the issue in my google searches.
