### ISSUE TITLE
Upgrading to the NiFi 2.0

### ISSUE THREAD

**Issue by peter279k** [saidsef/k8s-nifi-cluster#39]
As title, it seems that it uses the `NiFi 1.x` to build the cluster with the K8, do you have any plan to use the NiFi 2.0 to build the cluster with K8s? Thanks.

**Comment by saidsef** [comment]
Hi @peter279k, I've just started testing that this week with a view of releasing it once I'm sure the bootstrap works as expected.  With version 2.x there [breaking changes](https://cwiki.apache.org/confluence/display/NIFI/Release+Notes#ReleaseNotes-Version2.0.0).

So far, just minor changes, I think I'll skip 2.0 and release 2.1.x early next year.

Happy New Year 🎉

**Comment by peter279k** [comment]
Thanks for your reply. You can release new k8s-nifi-cluster for `2.1.x` version next year!

Happy New Year 🎆.

**Comment by peter279k** [comment]
@saidsef, I also have the [docker-compose-file.yml](https://github.com/peter279k/nifi_persistence/blob/master/docker-compose-file.yml) file and I think it can help you to upgrade to the NiFi `2.1.0` version :).

**Comment by saidsef** [comment]
@peter279k, locally I'm using [kind](https://kind.sigs.k8s.io/) for testing and deployment the Kubernetes manifests in deployment directory:
```bash
kind create cluster --name nifi
kubeclt apply -k deployment/
```

**Comment by peter279k** [comment]
@saidsef, thanks for your reply. I've used this `` branch to try to run the NiFi 2.0 cluster in my local K8s cluster.

I've the following problem when running the `k8s kubectl apply -f deployment/`. And the pod log output is as follows:

```
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  25m                 default-scheduler  Successfully assigned default/nifi-0 to openvpms
  Normal   Pulling    25m                 kubelet            Pulling image "docker.io/busybox:1.37"
  Normal   Pulled     25m                 kubelet            Successfully pulled image "docker.io/busybox:1.37" in 9.06s (9.06s including waiting). Image size: 2167089 bytes.
  Normal   Created    25m                 kubelet            Created container: wait-for-zookeeper
  Normal   Started    25m                 kubelet            Started container wait-for-zookeeper
  Normal   Pulling    24m                 kubelet            Pulling image "docker.io/apache/nifi:2.1.0"
  Normal   Pulled     23m                 kubelet            Successfully pulled image "docker.io/apache/nifi:2.1.0" in 1m50.223s (1m50.223s including waiting). Image size: 1106276699 bytes.
  Normal   Created    23m                 kubelet            Created container: nifi
  Normal   Started    23m                 kubelet            Started container nifi
  Warning  Unhealthy  82s (x48 over 21m)  kubelet            Readiness probe failed: dial tcp 10.1.0.180:11443: connect: connection refused
```

And the `nifi` pod has not been ready:

```
NAME          READY   STATUS    RESTARTS   AGE
nifi-0        0/1     Running   0          28m
zookeeper-0   1/1     Running   0          28m
```

Could you help me to check that? Thanks.

**Comment by peter279k** [comment]
@saidsef, after digging above issue, I've found the problem.

The `NIFI_CLUSTER_IS_NODE` configuration should be `true` in the `deployment/nifi/configmap.yml` file.

After doing above step, it will be worked successfully. But it presents the following error when using the `curl -k https://{nifi_cluster_ip or domain name}:8443` command:

```bash
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Invalid SNI</title>
</head>
<body>
<h2>HTTP ERROR 400 Invalid SNI</h2>
<table>
<tr><th>URI:</th><td>https://10.152.183.155:8443/</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Invalid SNI</td></tr>
</table>

</body>
</html>
```

The problem will present because the NiFi Cluster IP addressor specific domain name is not included in the self-signed truststore certificate.

To resolve issue, it should add the `-ext` option with the `SAN` configuration when using the `keytool` command to generate self-signed truststore.

**Comment by raghumuppa** [comment]
Hi @saidsef facing the below issue after deploying the nifi cluster, the issue is related to the SSL, tried adding the specific domain to the -ext SAN but still facing the issue.

The below logs from nifi-1, nifi-0 doestn't have any issues.

```
2025-02-12 09:34:15,503 WARN [main] o.a.nifi.controller.StandardFlowService Failed to connect to cluster
org.apache.nifi.cluster.protocol.ProtocolException: Failed marshalling 'CONNECTION_REQUEST' protocol message due to: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at org.apache.nifi.cluster.protocol.AbstractNodeProtocolSender.requestConnection(AbstractNodeProtocolSender.java:83)
        at org.apache.nifi.cluster.protocol.impl.NodeProtocolSenderListener.requestConnection(NodeProtocolSenderListener.java:89)
        at org.apache.nifi.controller.StandardFlowService.connect(StandardFlowService.java:827)
        at org.apache.nifi.controller.StandardFlowService.load(StandardFlowService.java:451)
        at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:922)
        at org.apache.nifi.runtime.Application.startServer(Application.java:131)
        at org.apache.nifi.runtime.Application.run(Application.java:78)
        at org.apache.nifi.runtime.Application.run(Application.java:60)
        at org.apache.nifi.NiFi.main(NiFi.java:42)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:206)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:922)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1291)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1263)
        at java.base/java.io.DataOutputStream.write(DataOutputStream.java:95)
        at org.apache.nifi.cluster.protocol.jaxb.JaxbProtocolContext.lambda$createMarshaller$0(JaxbProtocolContext.java:78)
        at org.apache.nifi.cluster.protocol.AbstractNodeProtocolSender.requestConnection(AbstractNodeProtocolSender.java:81)
        ... 8 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:318)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:267)
        at java.base/sun.security.validator.Validator.validate(Validator.java:256)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at org.apache.nifi.security.ssl.StandardX509ExtendedTrustManager.checkServerTrusted(StandardX509ExtendedTrustManager.java:61)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302)
        ... 24 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:157)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:313)
        ... 30 common frames omitted
```

**Comment by peter279k** [comment]
The above comment I've encountered and related discussions are as follows:

- https://github.com/saidsef/k8s-nifi-cluster/pull/41#issuecomment-2645261195
- https://github.com/saidsef/k8s-nifi-cluster/pull/41#issuecomment-2645719810

**Comment by S1mpleOW** [comment]
Is there any update on this new version of Nifi Cluster ? I really need to have a setup Nifi Cluster with 2.x.x version

**Comment by dev2-piniada** [comment]
i go the same issue 

026-01-20 08:16:35 2026-01-19 21:46:34,775 INFO [main] o.a.nifi.controller.StandardFlowService Connecting Node: nifi-1.nifi-headless.nifi.svc.cluster.local:8443
2026-01-20 08:16:35 2026-01-19 21:46:34,777 INFO [main] o.a.n.c.c.n.LeaderElectionNodeProtocolSender Determined that Cluster Coordinator is located at nifi-0.nifi-headless.nifi.svc.cluster.local:11443; will use this address for sending heartbeat messages
2026-01-20 08:16:35 2026-01-19 21:46:34,778 INFO [main] o.a.n.c.p.AbstractNodeProtocolSender Cluster Coordinator is located at nifi-0.nifi-headless.nifi.svc.cluster.local/<unresolved>:11443. Will send Cluster Connection Request to this address
2026-01-20 08:16:35 2026-01-19 21:46:34,847 WARN [main] o.a.nifi.controller.StandardFlowService Failed to connect to cluster
2026-01-20 08:16:35 org.apache.nifi.cluster.protocol.ProtocolException: Failed marshalling 'CONNECTION_REQUEST' protocol message due to: javax.net.ssl.SSLHandshakeException: (certificate_unknown) PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
2026-01-20 08:16:35     at org.apache.nifi.cluster.protocol.AbstractNodeProtocolSender.requestConnection(AbstractNodeProtocolSender.java:85)
2026-01-20 08:16:35     at org.apache.nifi.cluster.protocol.impl.NodeProtocolSenderListener.requestConnection(NodeProtocolSenderListener.java:91)
2026-01-20 08:16:35     at org.apache.nifi.controller.StandardFlowService.connect(StandardFlowService.java:811)
2026-01-20 08:16:35     at org.apache.nifi.controller.StandardFlowService.load(StandardFlowService.java:435)
2026-01-20 08:16:35     at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:843)
2026-01-20 08:16:35     at org.apache.nifi.runtime.Application.startServer(Application.java:131)
2026-01-20 08:16:35     at org.apache.nifi.runtime.Application.run(Application.java:78)
2026-01-20 08:16:35     at org.apache.nifi.runtime.Application.run(Application.java:60)
2026-01-20 08:16:35     at org.apache.nifi.NiFi.main(NiFi.java:42)
2026-01-20 08:16:35 Caused by: javax.net.ssl.SSLHandshakeException: (certificate_unknown) PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
2026-01-20 08:16:35     at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
2026-01-20 08:16:35     at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
2026-01-20 08:16:35     at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
2026-01-20 08:16:35     at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
2026-01-20 08:16:35     at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1287)
2026-01-20

**Comment by saidsef** [comment]
@peter279k / @raghumuppa  / @S1mpleOW this was delayed due to new baby 🍼 

I have update the outdated [PR](https://github.com/saidsef/k8s-nifi-cluster/pull/41) with NiFi v2.7 - I've deployed that in out local cluster - obviously with more resources in out production cluster. I will this further and merge the PR later this week.

**Comment by saidsef** [comment]
Resolved via #41
